---
title: "Seeking Help"
format: html
editor: visual
---

The exercises in this document follow along closely with [Lesson 3](https://swcarpentry.github.io/r-novice-gapminder/03-seeking-help.html) of [R for Reproducible Scientific Analysis](https://swcarpentry.github.io/r-novice-gapminder/), provided by the [Software Carpentry](https://software-carpentry.org/) community under the creative commons license, [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/). For more information see [The Carpentries](https://carpentries.org/).

### [Seeking Help](https://swcarpentry.github.io/r-novice-gapminder/03-seeking-help/index.html)

::: callout-tip
## Key Points

Use `help()` or `?` to get help in R.
:::

#### Challenge 1

Look at the help page for `c`. What kind of vector do you expect will be creeated if you evaluate the following?

```{r}
c(1, 2, 3)
c('d', 'e', 'f')
c(1, 2, 'f')
```

<!-- Challenge 1 answer begin -->

`c(1, 2, 3)` should give me a numeric vector.

`c('d', 'e', 'f')` should give me a character vector.

`c(1, 2, 'f')` should also give me a character vector, because numbers can be coerced to characters, but characters can't be coerced to a numeric value.

<!-- Challenge 1 answer end -->

#### Challenge 2

Look at the help for the `paste` function. You will need to use it later. What's the difference between the `sep` and `collapse` arguments?

<!-- Challenge 2 answer begin -->

`sep` allows you to change the default separator between each argument passed to `paste`. By default, `paste` returns a vector of character values, but when `collapse` is provided, the value for `collapse` is pasted between each value in the vector, which is collapsed into a single character value.

<!-- Challenge 2 answer end -->

#### Challenge 3

Use help to find a function (and its associated parameters) that you could use to load data from a tabular file in which columns are delimited with "\t\" (tab) and the decimal point is a"." (period). This check for decimal separator is important, especially if you are working with international colleagues, because different countries have different conventions for the decimal point (i.e. comma vs period).

::: {.callout-note collapse="true"}
# Hint

Use `??"read table"` to look up functions related to reading in tabular data.
:::

<!-- Challenge 3 answer begin -->

`read.delim` would be a good solution, or you could use `read.table` and specify `sep = '\t'`.

<!-- Challenge 3 answer end -->
